/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CollectedRouteImport } from './routes/collected'
import { Route as IndexRouteImport } from './routes/index'

const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectedRoute = CollectedRouteImport.update({
  id: '/collected',
  path: '/collected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collected': typeof CollectedRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collected': typeof CollectedRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collected': typeof CollectedRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collected' | '/search' | '/series'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collected' | '/search' | '/series'
  id: '__root__' | '/' | '/collected' | '/search' | '/series'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectedRoute: typeof CollectedRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collected': {
      id: '/collected'
      path: '/collected'
      fullPath: '/collected'
      preLoaderRoute: typeof CollectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectedRoute: CollectedRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
